TheCoreBanking 2.0/TheCoreBanking/Controllers/ApprovingAuthorityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheCoreBanking.Data.Contracts;
using TheCoreBanking.Data.Models;
using TheCoreBanking.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheCoreBanking.Data.Helpers;

namespace TheCoreBanking.Controllers
{
    public class ApprovingAuthorityController : Controller
    {

        private readonly TheCoreBankingContext _context;
        public ApprovingAuthorityController(ISetupUnitOfWork uowSetup)
        {
            setupUnitOfWork = uowSetup;
        }

        public ISetupUnitOfWork setupUnitOfWork { get; set; }





        public IActionResult Index()
        {
            return View();
        }




        [HttpGet]
        public JsonResult LoadOppApproval()
        {
            var result = setupUnitOfWork.OpeApprove.GetAll();

            List<OperationApprovalVM> OperationAppVM = new List<OperationApprovalVM>();

            foreach (var item in result)
            {
                OperationApprovalVM opViewModel = new OperationApprovalVM();
                var operations = setupUnitOfWork.OperationLevel.GetAll().Where(i => i.OperationId == item.OperationId).Select(m => m.Operations).FirstOrDefault();
                var levels = setupUnitOfWork.OperationLevel.GetAll().Where(i => i.OperationId == item.OperationId).Select(m => m.ApprovalLevels).FirstOrDefault();
                opViewModel.Id = item.Id;
                opViewModel.MaxAmt = item.MaxAmt;
                opViewModel.MinAmt = item.MinAmt;
                opViewModel.Designation = item.Designation;
                opViewModel.CummulativeAmt = item.CummulativeAmt;
                opViewModel.ApprovingAuthority = item.ApprovingAuthority;
                opViewModel.ApprovingLevel = item.ApprovingLevel;
                opViewModel.StaffId = item.StaffId;
                opViewModel.BranchCode = item.BranchCode;
                opViewModel.CompanyCode = item.CompanyCode;
                opViewModel.CreatedBy = item.CreatedBy;

                opViewModel.Operations = operations;
                ViewBag.Message = levels;


                OperationAppVM.Add(opViewModel);

            }
            return Json(OperationAppVM);


        }



        [HttpPost]
        public JsonResult AddOpeOthers(OperationApprovalVM opeothers)
        {

            Data.Models.TblOperationApproval addOP = new Data.Models.TblOperationApproval();

            var count = (setupUnitOfWork.OpeApprove.GetAll().Where(o => o.ApprovingAuthority == opeothers.StaffName && o.OperationId == opeothers.OperationId).Select(o => o.CommitteeType).Count());


            if (count > 0)
            {

                return Json(false);
            }

            else
            {
                var loguser = User.Identity.Name;
                if (loguser == null)
                {
                    loguser = "tayo.olawumi";
                }
                else
                {
                    loguser = User.Identity.Name;
                }

                var branch = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == loguser).FirstOrDefault().BranchId;

                var company = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == loguser).FirstOrDefault().CompanyId;

                var staffno = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == opeothers.StaffName).FirstOrDefault().StaffNo;

                addOP.CreatedBy = loguser;
                addOP.ApprovingAuthority = opeothers.StaffName;
                addOP.ApprovingLevel = opeothers.ApprovingLevel;
                addOP.BranchCode = branch;
                addOP.CommitteeType = "O";
                addOP.CompanyCode = company;
                addOP.CreateDate = DateTime.Now;
                addOP.CummulativeAmt = opeothers.CummulativeAmt;
                addOP.Designation = opeothers.Designation;
                addOP.MaxAmt = opeothers.MaxAmt;
                addOP.MinAmt = opeothers.MinAmt;
                addOP.OperationId = opeothers.OperationId;
                addOP.StaffId = staffno;
                addOP.Approved = false;
                addOP.Disapproved = false;

                setupUnitOfWork.OpeApprove.Add(addOP);
                setupUnitOfWork.Commit();

                //return Json(opeothers);
                return Json(true);
            }
            // return Json(new { message = ViewBag.Reply });
        }        






        [HttpGet]
        public JsonResult LoadOperate()
        {

            var list = new List<SelectTwoContentM>();
            var result = setupUnitOfWork.OperationLevel.GetAll();


            foreach (var item in result)
            {

                list.Add(new SelectTwoContentM
                {
                    id = Convert.ToString(item.OperationId),
                    text = item.Operations,
                });

            }

            return Json(list);
        }



        [HttpGet]
        public JsonResult AppLevel(int id)
        {
            List<ApplevelVM> applevelViewModel = new List<ApplevelVM>();
            var result = setupUnitOfWork.OperationLevel.GetAll().Where(m => m.OperationId == id);

            List<int> applevelForSelect2Input = new List<int>();

            var count = result.FirstOrDefault().ApprovalLevels;

            for (var i = 1; i <= count; i++)
            {

                var approvinglev = new ApplevelVM()
                {
                    id = i.ToString(),
                    text = Convert.ToString(i)
                };
                applevelViewModel.Add(approvinglev);
            }

            //foreach (var item in result)
            //{
            //    var approvinglev = new ApplevelVM()
            //    {
            //        id = item.Operations,
            //        text = Convert.ToString(item.ApprovalLevels)
            //    };
            //    applevelViewModel.Add(approvinglev);
            //}
            return Json(applevelViewModel);
        }



        [HttpGet]
        public JsonResult GetDesignation()
        {

            var list = new List<SelectTwoContentM>();
            var result = setupUnitOfWork.Designation.GetAll();


            foreach (var item in result)
            {

                list.Add(new SelectTwoContentM
                {
                    id = item.Id.ToString(),
                    text = item.Designation

                });

            }

            return Json(list);
        }



        [HttpGet]
        public JsonResult LoadStaff(int id)
        {
            List<OperateAppSetupVM> OpeViewModel = new List<OperateAppSetupVM>();
            var result = setupUnitOfWork.Staff.GetAll().Where(m => m.DesignationCode == id);
            //var results = setupUnitOfWork.Designation.GetAll().Where(m => m.Id == result.DesignationCode);



            foreach (var item in result)
            {
                var departmentalStaff = new OperateAppSetupVM()
                {
                    id = setupUnitOfWork.Designation.GetAll().Where(m => m.Id == item.DesignationCode).Select(m => m.Designation).FirstOrDefault(),
                    text = item.StaffName,
                };
                OpeViewModel.Add(departmentalStaff);
            }
            return Json(OpeViewModel);
        }





        public class SelectTwoContentM
        {
            public string id { get; set; }
            public string text { get; set; }
        }
    }
}

TheCoreBanking 2.0/TheCoreBanking/Views/ApprovingAuthority/Index.cshtml
@model TheCoreBanking.Data.Models.TblOperationApprovalCommittee




@section pagedescription{
    <span class="title f24px">GENERAL SET UP M0DULE</span>
}


<div class="card">

    <div class="card-body">
        <div class="card-header ">
            <h4 class="card-title text-center"> <small class="description">APPROVING AUTHORITY SET UP</small></h4>
        </div>


        <div id="other-toolbar">
            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#btnCreateother" id="btncreateotheeop" name="btncreateotheeop"><i class="fas fa-plus"></i>Add Officer</button>
        </div>

        <table id="Other-Table" data-toggle="table" class="data-table"
               data-url="@Url.Action("LoadOppApproval","ApprovingAuthority")"
               data-search="true"
               data-search-align="right"
               data-show-export="true"
               data-toolbar="#other-toolbar"
               data-mobile-responsive="true"
               data-show-refresh="true"
               data-click-to-select="true"
               data-single-select="true"
               data-show-toggle="true"
               data-show-columns="true"
               data-detail-formatter="detailFormatter"
               data-unique-id="Id"
               data-detail-view="true"
               data-check-on-init="true"
               data-pagination="true"
               data-buttons-class="danger">
            <thead>
                <tr>
                    <th data-field="operations" data-align="center">Operation</th>
                    <th data-field="approvingAuthority" data-align="center">Officer</th>
                    <th data-field="staffId" data-align="center" data-visible="true">Staff No</th>
                    <th data-field="designation" data-align="center" data-visible="true">Designation</th>
                    <th data-field="approvalLevels" data-align="center" data-visible="false">Approval Levels</th>
                    <th data-field="minAmt" data-align="center">Min.Amount</th>
                    <th data-field="maxAmt" data-align="center" data-visible="true">Max.Amount</th>
                    <th data-field="cummulativeAmt" data-align="center" data-visible="true">Cul.Amount</th>
                    <th data-field="approvingLevel" data-align="center" data-visible="true">Approving Level</th>
                </tr>
            </thead>
        </table>


    </div>
</div>





<div id="btnCreateother" class="modal fade" role="dialog" data-backdrop="false" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" id="btncloseother" name="btncloseother">&times;</button>
                <h7 class="modal-title">Add Officer</h7>

            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col card card-plain">

                            <form id="others-form">
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Operation:
                                        <select class="form-control text-right" name="operations" required id="operations">
                                            <option>Select Operation</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        Designation:
                                        <select class="form-control text-right" name="designation" required id="designation">
                                            <option>Select Designation</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Approving Authority
                                        <select class="form-control text-right" name="authority" required id="authority">
                                            <option>Select Staff</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        Cummulative limit
                                        <input id="culLimit" name="culLimit" type="text" class="form-control text-right" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Minimum Amount
                                        <input id="minamount" name="minamount" type="number" class="form-control text-right" />
                                    </div>
                                    <div class="form-group col-md-6">
                                        Maximum Amount
                                        <input id="maxamount" name="maxamount" type="number" class="form-control text-right" />
                                    </div>
                                </div>
                                <div class="row">

                                    <div class="form-group col-md-6">
                                        Approving Level:
                                        <select class="form-control text-right" name="applevel" required id="applevel">
                                            <option>Select Approving level</option>
                                        </select>
                                    </div>

                                </div>
                                <div class="form-group text-right">
                                    <button class="btn btn-info" id="btnothers" type="submit" value="Save Record">
                                        <i class="now-ui-icons ui-1_check"></i>
                                        Save Record
                                    </button>
                                    <button class="btn btn-danger" type="button" id="btnclearother" onclick="clearO()">
                                        <i class="fa fa-recycle"></i>
                                        Clear
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>






@section Scripts {
    <environment include="Development">
        <script src="~/js/approvalmanager.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/approvalmanager.min.js"></script>
    </environment>
}