TheCoreBanking 2.0/TheCoreBanking/Controllers/BoardAuthorityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheCoreBanking.Data.Contracts;
using TheCoreBanking.Data.Models;
using TheCoreBanking.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheCoreBanking.Data.Helpers;


namespace TheCoreBanking.Controllers
{
    public class BoardAuthorityController : Controller
    {
        private readonly TheCoreBankingContext _context;
        public BoardAuthorityController(ISetupUnitOfWork uowSetup)
        {
            setupUnitOfWork = uowSetup;
        }

        public ISetupUnitOfWork setupUnitOfWork { get; set; }




        public IActionResult Index()
        {
            return View();
        }




        [HttpGet]
        public JsonResult listCommitBoard()
        {
            var result = setupUnitOfWork.ApprovalCommittee.GetAll().Where(o => o.CommitteeType == "B");

            List<CommitteeApprovalVM> BoardAppVM = new List<CommitteeApprovalVM>();

            foreach (var item in result)
            {
                CommitteeApprovalVM brdViewModel = new CommitteeApprovalVM();
                var operations = setupUnitOfWork.OperationLevel.GetAll().Where(i => i.OperationId == item.OperationId).Select(m => m.Operations).FirstOrDefault();
                brdViewModel.Id = item.Id;
                brdViewModel.CreditMaxBoardAmt = item.CreditMaxBoardAmt;
                brdViewModel.CreditMinBoard = item.CreditMinBoard;
                brdViewModel.Department = item.Department;
                brdViewModel.CummulativeAmt = item.CummulativeAmt;
                brdViewModel.ApprovingAuthority = item.ApprovingAuthority;
                brdViewModel.ApprovingLevel = item.ApprovingLevel;
                brdViewModel.StaffId = item.StaffId;
                brdViewModel.BranchCode = item.BranchCode;
                brdViewModel.CompanyCode = item.CompanyCode;
                //brdViewModel.CreatedBy = item.CreatedBy;
                brdViewModel.BoardNo = item.BoardNo;


                brdViewModel.Operations = operations;

                BoardAppVM.Add(brdViewModel);

            }

            return Json(BoardAppVM);

        }





        [HttpPost]
        public JsonResult AddComBoard(CommitteeApprovalVM bod)
        {

            Data.Models.TblOperationApprovalCommittee addbod = new Data.Models.TblOperationApprovalCommittee();
            var bodcomm = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId);
            if (bodcomm.Count() > 0)
            {
                var count = (setupUnitOfWork.ApprovalCommittee.GetAll().Where(o => o.ApprovingAuthority == bod.StaffName && o.OperationId == bod.OperationId && o.CommitteeType.Contains("B")).Select(o => o.CommitteeType).Count());
                //var checkLevel = (setupUnitOfWork.OpeApprove.GetAll().Where(o => o.OperationId == opeothers.OperationId && o.CommitteeType == "O" && o.ApprovingLevel == opeothers.ApprovingLevel).Count());
                // var levels = setupUnitOfWork.OperationLevel.GetAll().Where(i => i.OperationId == opeothers.OperationId).Select(m => m.ApprovalLevels).FirstOrDefault();
                if (count > 0)
                {
                    return Json(false);
                }


                else
                {
                    var loguser = User.Identity.Name;
                    if (loguser == null)
                    {
                        loguser = "tayo.olawumi";
                    }
                    else
                    {
                        loguser = User.Identity.Name;
                    }

                    var branch = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == loguser).FirstOrDefault().BranchId;

                    var company = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == loguser).FirstOrDefault().CompanyId;

                    var staffno = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == bod.StaffName).FirstOrDefault().StaffNo;

                    var mannum = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId).FirstOrDefault().MgtNo;

                    var mgtmin = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId).FirstOrDefault().CreditMinMgt;

                    var mgtmax = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId).FirstOrDefault().CreditMaxComteeAmt;

                    var bodno = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId).FirstOrDefault().BoardNo;

                    var bodappnum = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId).FirstOrDefault().BoardNoApproval;

                    var mgtappno = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId).FirstOrDefault().MgtNoApproval;

                    var credbodminamt = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId).FirstOrDefault().CreditMinBoard;

                    var credbodmax = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == bod.OperationId).FirstOrDefault().CreditMaxBoardAmt;

                    addbod.CreatedBy = loguser;
                    addbod.ApprovingAuthority = bod.StaffName;
                    addbod.ApprovingLevel = bod.ApprovingLevel;
                    addbod.BranchCode = branch;
                    addbod.CommitteeType = "B";
                    addbod.CompanyCode = company;
                    addbod.CreateDate = DateTime.Now;
                    addbod.CummulativeAmt = bod.CummulativeAmt;
                    addbod.Department = bod.Department;
                    addbod.MaxAmt = bod.MaxAmt;
                    addbod.MinAmt = bod.MinAmt;
                    addbod.BoardNo = bodno;
                    addbod.CreditMinBoard = credbodminamt;
                    addbod.CreditMaxBoardAmt = credbodmax;
                    addbod.BoardNoApproval = bodappnum;
                    addbod.MgtNoApproval = mgtappno;
                    addbod.MgtNo = mannum;
                    addbod.CreditMinMgt = mgtmin;
                    addbod.CreditMaxComteeAmt = mgtmax;
                    addbod.OperationId = bod.OperationId;
                    addbod.StaffId = staffno;
                    addbod.Approved = false;
                    addbod.Disapproved = false;


                    setupUnitOfWork.ApprovalCommittee.Add(addbod);
                    setupUnitOfWork.Commit();

                    return Json(true);
                }
            }
            else
            {
                return Json(false);
            }
        }



        [HttpGet]
        public JsonResult GetOperation()
        {

            var list = new List<SelectTwoContentM>();

            var result = setupUnitOfWork.OperationLevel.GetAll();
            foreach (var item in result)
            {
                list.Add(new SelectTwoContentM
                {
                    id = Convert.ToString(item.OperationId),
                    text = item.Operations,
                });
            }
            return Json(list);
        }




        [HttpGet]
        public JsonResult AppLevel(int id)
        {
            List<ApplevelVM> applevelViewModel = new List<ApplevelVM>();
            var result = setupUnitOfWork.OperationLevel.GetAll().Where(m => m.OperationId == id);

            List<int> applevelForSelect2Input = new List<int>();

            var count = result.FirstOrDefault().ApprovalLevels;

            for (var i = 1; i <= count; i++)
            {

                var approvinglev = new ApplevelVM()
                {
                    id = i.ToString(),
                    text = Convert.ToString(i)
                };
                applevelViewModel.Add(approvinglev);
            }

            //foreach (var item in result)
            //{
            //    var approvinglev = new ApplevelVM()
            //    {
            //        id = item.Operations,
            //        text = Convert.ToString(item.ApprovalLevels)
            //    };
            //    applevelViewModel.Add(approvinglev);
            //}
            return Json(applevelViewModel);
        }



        [HttpGet]
        public JsonResult LoadDeptStaff(string id)
        {
            List<CommitteeDepartmentVM> deptViewModel = new List<CommitteeDepartmentVM>();
            var result = setupUnitOfWork.Staff.GetAll().Where(m => m.DeptCode == id);



            foreach (var item in result)
            {
                var departmentalStaff = new CommitteeDepartmentVM()
                {
                    id = item.Department,
                    text = item.StaffName
                };
                deptViewModel.Add(departmentalStaff);
            }
            return Json(deptViewModel);
        }




        [HttpGet]
        public JsonResult GetDepartment()
        {

            var list = new List<SelectTwoContentM>();
            var result = setupUnitOfWork.Staff.GetAll().Select(o => new { DeptCode = o.DeptCode, Department = o.Department }).Distinct();

            foreach (var item in result)
            {

                list.Add(new SelectTwoContentM
                {
                    id = Convert.ToString(item.DeptCode),
                    text = item.Department,

                });

            }

            return Json(list);
        }









        public class SelectTwoContentM
        {
            public string id { get; set; }
            public string text { get; set; }
        }


    }
}

TheCoreBanking 2.0/TheCoreBanking/Views/BoardAuthority/Index.cshtml
@model TheCoreBanking.Data.Models.TblOperationApprovalCommittee




@section pagedescription{
    <span class="title f24px">GENERAL SET UP M0DULE</span>
}


<div class="card">

    <div class="card-body">
        <div class="card-header ">
            <h4 class="card-title text-center"> <small class="description">APPROVING AUTHORITY SET UP</small></h4>
        </div>

        <div id="custom-toolbar">
            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#btnCreateboard" id="btnaddbod" name="btnaddbod"><i class="fas fa-plus"></i>Add Officer</button>
        </div>

        <table id="data-table" data-toggle="table" class="data-table"
               data-url="@Url.Action("listCommitBoard","BoardAuthority")"
               data-search="true"
               data-search-align="right"
               data-show-export="true"
               data-toolbar="#custom-toolbar"
               data-mobile-responsive="true"
               data-show-refresh="true"
               data-click-to-select="true"
               data-single-select="true"
               data-show-toggle="true"
               data-show-columns="true"
               data-detail-formatter="detailFormatter"
               data-unique-id="id"
               data-detail-view="true"
               data-check-on-init="true"
               data-pagination="true"
               data-buttons-class="danger">
            <thead>
                <tr>
                    <th data-field="operations" data-align="center">Operation</th>
                    <th data-field="approvingAuthority" data-align="center">Officer</th>
                    <th data-field="staffId" data-align="center" data-visible="true">Staff No</th>
                    <th data-field="department" data-align="center" data-visible="true">Department</th>
                    <th data-field="creditMinBoard" data-align="center">Min.Amount</th>
                    <th data-field="creditMaxBoardAmt" data-align="center" data-visible="true">Max.Amount</th>
                    <th data-field="cummulativeAmt" data-align="center" data-visible="true">Cul.Amount</th>
                    <th data-field="approvingLevel" data-align="center" data-visible="true">Approving Level</th>

                </tr>
            </thead>
        </table>


    </div>
</div>







<div id="btnCreateboard" class="modal fade" role="dialog" data-backdrop="false" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" id="closeboard" name="closeboard">&times;</button>
                <h7 class="modal-title">Add Officer</h7>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col card card-plain">
                            <form id="Create-Group-form">
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Operation:
                                        <select class="form-control text-right" name="bodOperation" required id="bodOperation">
                                            <option>Select Operation</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        Designation:
                                        <select class="form-control text-right" name="boddepartment" required id="boddepartment">
                                            <option>Select Department</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Approving Authority
                                        <select class="form-control text-right" name="bodauthority" required id="bodauthority">
                                            <option>Select Staff</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        Cummulative limit
                                        <input id="bodculLimit" name="bodculLimit" type="text" class="form-control text-right" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Minimum Amount
                                        <input id="bodminamount" name="bodminamount" type="number" class="form-control text-right" />
                                    </div>
                                    <div class="form-group col-md-6">
                                        Maximum Amount
                                        <input id="bodmaxamount" name="bodmaxamount" type="number" class="form-control text-right" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Approving Level:
                                        <select class="form-control text-right" name="bodapplevel" required id="bodapplevel">
                                            <option>Select Approving level</option>
                                        </select>
                                    </div>

                                </div>
                                <div class="form-group text-right">
                                    <button class="btn btn-info" id="btnbrdapp" type="submit" value="Save Record">
                                        <i class="now-ui-icons ui-1_check"></i>
                                        Save Record
                                    </button>
                                    <button class="btn btn-danger" type="button" id="btnclearboard" onclick="clearB()">
                                        <i class="fa fa-recycle"></i>Clear
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>















@section Scripts {
    <environment include="Development">
        <script src="~/js/authoritybod.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/authoritybod.min.js"></script>
    </environment>
}