TheCoreBanking 2.0/TheCoreBanking/Controllers/AuthorityCommitteeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheCoreBanking.Data.Contracts;
using TheCoreBanking.Data.Models;
using TheCoreBanking.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheCoreBanking.Data.Helpers;

namespace TheCoreBanking.Controllers
{
    public class AuthorityCommitteeController : Controller
    {

        private readonly TheCoreBankingContext _context;
        public AuthorityCommitteeController(ISetupUnitOfWork uowSetup)
        {
            setupUnitOfWork = uowSetup;
        }

        public ISetupUnitOfWork setupUnitOfWork { get; set; }



        public IActionResult Index()
        {
            return View();
        }



        public JsonResult listCommitMgt()
        {

            var result = setupUnitOfWork.ApprovalCommittee.GetAll().Where(o => o.CommitteeType == "M");

            List<CommitteeApprovalVM> ManagementAppVM = new List<CommitteeApprovalVM>();

            foreach (var item in result)
            {
                CommitteeApprovalVM manViewModel = new CommitteeApprovalVM();
                var operations = setupUnitOfWork.OperationLevel.GetAll().Where(i => i.OperationId == item.OperationId).Select(m => m.Operations).FirstOrDefault();

                manViewModel.Id = item.Id;
                manViewModel.CreditMaxComteeAmt = item.CreditMaxComteeAmt;
                manViewModel.CreditMinMgt = item.CreditMinMgt;
                manViewModel.Department = item.Department;
                manViewModel.CummulativeAmt = item.CummulativeAmt;
                manViewModel.ApprovingAuthority = item.ApprovingAuthority;
                manViewModel.ApprovingLevel = item.ApprovingLevel;
                manViewModel.StaffId = item.StaffId;
                manViewModel.BranchCode = item.BranchCode;
                manViewModel.CompanyCode = item.CompanyCode;
                manViewModel.BoardNo = item.BoardNo;
                //manViewModel.CreatedBy = item.CreatedBy;

                manViewModel.Operations = operations;

                ManagementAppVM.Add(manViewModel);

            }

            return Json(ManagementAppVM);

        }




        [HttpPost]
        public JsonResult AddComMgt(CommitteeApprovalVM man)
        {

            Data.Models.TblOperationApprovalCommittee addman = new Data.Models.TblOperationApprovalCommittee();
            var comm = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId);
            if (comm.Count() > 0)
            {
                var count = (setupUnitOfWork.ApprovalCommittee.GetAll().Where(o => o.ApprovingAuthority == man.StaffName && o.OperationId == man.OperationId && o.CommitteeType.Contains("M")).Select(o => o.CommitteeType).Count());
                //var checkLevel = (setupUnitOfWork.OpeApprove.GetAll().Where(o => o.OperationId == opeothers.OperationId && o.CommitteeType == "O" && o.ApprovingLevel == opeothers.ApprovingLevel).Count());

                if (count > 0)
                {
                    return Json(false);
                }

                else
                {
                    var loguser = User.Identity.Name;
                    if (loguser == null)
                    {
                        loguser = "tayo.olawumi";
                    }
                    else
                    {
                        loguser = User.Identity.Name;
                    }

                    var branch = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == loguser).FirstOrDefault().BranchId;

                    var company = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == loguser).FirstOrDefault().CompanyId;

                    var staffno = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == man.StaffName).FirstOrDefault().StaffNo;

                    var mannum = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId).FirstOrDefault().MgtNo;

                    var credmgtminamt = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId).FirstOrDefault().CreditMinMgt;

                    var credmgtmax = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId).FirstOrDefault().CreditMaxComteeAmt;

                    var credminbod = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId).FirstOrDefault().CreditMinBoard;

                    var bodno = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId).FirstOrDefault().BoardNo;

                    var credmaxbodamt = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId).FirstOrDefault().CreditMaxBoardAmt;

                    var mgtappno = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId).FirstOrDefault().MgtNoApproval;

                    var bodappno = setupUnitOfWork.Committee.GetAll().Where(i => i.OperationId == man.OperationId).FirstOrDefault().BoardNoApproval;

                    addman.CreatedBy = loguser;
                    addman.ApprovingAuthority = man.StaffName;
                    addman.ApprovingLevel = man.ApprovingLevel;
                    addman.BranchCode = branch;
                    //addgroup.CommitteeType = opeothers.CommitteeType;
                    addman.CompanyCode = company;
                    addman.CreateDate = DateTime.Now;
                    addman.CummulativeAmt = man.CummulativeAmt;
                    addman.Department = man.Department;
                    addman.CreditMaxComteeAmt = credmgtmax;
                    addman.CreditMinMgt = credmgtminamt;
                    addman.OperationId = man.OperationId;
                    addman.MinAmt = man.MinAmt;
                    addman.MaxAmt = man.MaxAmt;
                    addman.StaffId = staffno;
                    addman.CommitteeType = "M";
                    addman.Approved = false;
                    addman.Disapproved = false;

                    addman.MgtNo = mannum;
                    addman.CreditMinBoard = credminbod;
                    addman.BoardNo = bodno;
                    addman.CreditMaxBoardAmt = credmaxbodamt;
                    addman.OperationId = man.OperationId;
                    addman.MgtNoApproval = mgtappno;
                    addman.BoardNoApproval = bodappno;

                    setupUnitOfWork.ApprovalCommittee.Add(addman);
                    setupUnitOfWork.Commit();

                    return Json(true);
                }
            }
            else
            {
                return Json(false);
            }
        }






        [HttpGet]
        public JsonResult GetOperation()
        {

            var list = new List<SelectTwoContentM>();

            var result = setupUnitOfWork.OperationLevel.GetAll();
            foreach (var item in result)
            {
                list.Add(new SelectTwoContentM
                {
                    id = Convert.ToString(item.OperationId),
                    text = item.Operations,
                });
            }
            return Json(list);
        }




        [HttpGet]
        public JsonResult AppLevel(int id)
        {
            List<ApplevelVM> applevelViewModel = new List<ApplevelVM>();
            var result = setupUnitOfWork.OperationLevel.GetAll().Where(m => m.OperationId == id);

            List<int> applevelForSelect2Input = new List<int>();

            var count = result.FirstOrDefault().ApprovalLevels;

            for (var i = 1; i <= count; i++)
            {

                var approvinglev = new ApplevelVM()
                {
                    id = i.ToString(),
                    text = Convert.ToString(i)
                };
                applevelViewModel.Add(approvinglev);
            }

            //foreach (var item in result)
            //{
            //    var approvinglev = new ApplevelVM()
            //    {
            //        id = item.Operations,
            //        text = Convert.ToString(item.ApprovalLevels)
            //    };
            //    applevelViewModel.Add(approvinglev);
            //}
            return Json(applevelViewModel);
        }



        [HttpGet]
        public JsonResult LoadDeptStaff(string id)
        {
            List<CommitteeDepartmentVM> deptViewModel = new List<CommitteeDepartmentVM>();
            var result = setupUnitOfWork.Staff.GetAll().Where(m => m.DeptCode == id);



            foreach (var item in result)
            {
                var departmentalStaff = new CommitteeDepartmentVM()
                {
                    id = item.Department,
                    text = item.StaffName
                };
                deptViewModel.Add(departmentalStaff);
            }
            return Json(deptViewModel);
        }




        [HttpGet]
        public JsonResult GetDepartment()
        {

            var list = new List<SelectTwoContentM>();
            var result = setupUnitOfWork.Staff.GetAll().Select(o => new { DeptCode = o.DeptCode, Department = o.Department }).Distinct();

            foreach (var item in result)
            {

                list.Add(new SelectTwoContentM
                {
                    id = Convert.ToString(item.DeptCode),
                    text = item.Department,

                });

            }

            return Json(list);
        }






        public class SelectTwoContentM
        {
            public string id { get; set; }
            public string text { get; set; }
        }
    }
}

TheCoreBanking 2.0/TheCoreBanking/Views/AuthorityCommittee/Index.cshtml
@model TheCoreBanking.Data.Models.TblOperationApprovalCommittee




@section pagedescription{
    <span class="title f24px">GENERAL SET UP M0DULE</span>
}


@*<div class="card">

    <div class="card-body">
        <div class="card-header ">
            <h4 class="card-title text-center"> <small class="description">APPROVING AUTHORITY SET UP</small></h4>
        </div>


        <div id="custom-toolbar">
            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#CreateManagement" id="btnaddman" name="btnaddman"><i class="fas fa-plus"></i>Add Officer</button>
        </div>

        <table id="data-table" data-toggle="table" class="data-table"
               data-url="@Url.Action("listCommitMgt","AuthorityCommittee")"
               data-search="true"
               data-search-align="right"
               data-show-export="true"
               data-toolbar="#custom-toolbar"
               data-mobile-responsive="true"
               data-show-refresh="true"
               data-click-to-select="true"
               data-single-select="true"
               data-show-toggle="true"
               data-show-columns="true"
               data-detail-formatter="detailFormatter"
               data-unique-id="id"
               data-detail-view="true"
               data-check-on-init="true"
               data-pagination="true"
               data-buttons-class="danger">
            <thead>
                <tr>
                    <th data-field="operations" data-align="center">Operation</th>
                    <th data-field="approvingAuthority" data-align="center">Officer</th>
                    <th data-field="staffId" data-align="center" data-visible="true">Staff No</th>
                    <th data-field="department" data-align="center" data-visible="true">Department</th>
                    <th data-field="creditMinMgt" data-align="center">Min.Amount</th>
                    <th data-field="creditMaxComteeAmt" data-align="center" data-visible="true">Max.Amount</th>
                    <th data-field="cummulativeAmt" data-align="center" data-visible="true">Cul.Amount</th>
                    <th data-field="approvingLevel" data-align="center" data-visible="true">Approving Level</th>
                </tr>
            </thead>
        </table>



    </div>
</div>*@




<div class="card" id="customer-card">
        <div class="card-header text-center">
            <h4 class="card-title">APPROVING AUTHORITY SET UP</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="card card-plain">
                    <div class="card-body">

                        <div id="custom-toolbar">
                            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#CreateManagement" id="btnaddman" name="btnaddman"><i class="fas fa-plus"></i>Add Officer</button>
                        </div>


                        <table id="data-table"
                               data-unique-id="id"
                               class="data-table"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>





<div id="CreateManagement" class="modal fade" role="dialog" data-backdrop="false" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" id="btnclosemanage" name="btnclosemanage">&times;</button>
                <h7 class="modal-title">Add Officer</h7>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col card card-plain">
                            <form id="Create-Group">
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Operation:
                                        <select class="form-control text-right" name="ManOperation" required id="ManOperation">
                                            <option>Select Operation</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        Department:
                                        <select class="form-control text-right" name="Mandepartment" required id="Mandepartment">
                                            <option>Select Department</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Approving Authority
                                        <select class="form-control text-right" name="Manauthority" required id="Manauthority">
                                            <option>Select Staff</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        Cummulative limit
                                        <input id="ManculLimit" name="ManculLimit" type="text" class="form-control text-right" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Minimum Amount
                                        <input id="Manminamount" name="Manminamount" type="number" class="form-control text-right" />
                                    </div>
                                    <div class="form-group col-md-6">
                                        Maximum Amount
                                        <input id="Manmaxamount" name="Manmaxamount" type="number" class="form-control text-right" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Approving Level:
                                        <select class="form-control text-right" name="manapplevel" required id="manapplevel">
                                            <option>Select Approving level</option>
                                        </select>
                                    </div>

                                </div>
                                <div class="form-group text-right">
                                    <button class="btn btn-info" id="btnmanapp" type="submit" value="Save Record">
                                        <i class="now-ui-icons ui-1_check"></i>
                                        Save Record
                                    </button>
                                    <button class="btn btn-danger" type="button" id="btnclearmanage" onclick="clearM">
                                        <i class="fa fa-recycle"></i>
                                        Clear
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts {
    <environment include="Development">
        <script src="~/js/authoritycommittee.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/authoritycommittee.min.js"></script>
    </environment>
}