TheCoreBanking 2.0/TheCoreBanking/Controllers/ApprovalCommitteeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheCoreBanking.Data.Contracts;
using TheCoreBanking.Data.Models;
using TheCoreBanking.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheCoreBanking.Data.Helpers;


namespace TheCoreBanking.Controllers
{
    public class ApprovalCommitteeController : Controller
    {
        private readonly TheCoreBankingContext _context;
        public ApprovalCommitteeController(ISetupUnitOfWork uowSetup)
        {
            setupUnitOfWork = uowSetup;
        }

        public ISetupUnitOfWork setupUnitOfWork { get; set; }



        public IActionResult Index()
        {
            return View();
        }




        //LIST COMMITTEE

        public JsonResult listcommittee()
        {

            /*var results = setupUnitOfWork.Committee.GetAll();*/
            var results = setupUnitOfWork.Committee.GetAll().GroupBy(b => b.OperationId).Select(b => b.FirstOrDefault());

            //var results = setupUnitOfWork.Committee.GetAll();

            List<CommitteeApprovalVM> ComAppVM = new List<CommitteeApprovalVM>();

            foreach (var item in results)
            {

                CommitteeApprovalVM ComViewModel = new CommitteeApprovalVM();
                ComViewModel.MgtNo = item.MgtNo;
                ComViewModel.MgtNoApproval = item.MgtNoApproval;
                ComViewModel.BoardNo = item.BoardNo;
                ComViewModel.BoardNoApproval = item.BoardNoApproval;
                ComViewModel.CreditMinMgt = item.CreditMinMgt;
                ComViewModel.CreditMaxComteeAmt = item.CreditMaxComteeAmt;
                ComViewModel.CreditMinBoard = item.CreditMinBoard;
                ComViewModel.CreditMaxBoardAmt = item.CreditMaxBoardAmt;
                ComViewModel.Committee = item.Committee;
                ComViewModel.Createdby = item.Createdby;
                ComAppVM.Add(ComViewModel);

            }


            return Json(results);


        }


        [HttpPost]
        public JsonResult PostCommittee(TblBankingCommittee commit)
        {

            TblBankingCommittee addcommit = new TblBankingCommittee();

            var loguser = User.Identity.Name;
            if (loguser == null)
            {
                loguser = "tayo.olawumi";
            }
            else
            {
                loguser = User.Identity.Name;
            }

            var branch = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == loguser).FirstOrDefault().BranchId;

            var company = setupUnitOfWork.Staff.GetAll().Where(i => i.StaffName == loguser).FirstOrDefault().CompanyId;

            //if (committee.MgtNo.ToString() == "" || committee.MgtNo.ToString() == "0" || committee.MgtNo.ToString() == null)
            if (commit.BoardNo.ToString() == "" || commit.BoardNo.ToString() == "0" || commit.BoardNo.ToString() == null)
            {
                addcommit.CreditMaxComteeAmt = commit.CreditMaxComteeAmt;
                addcommit.CreditMinMgt = commit.CreditMinMgt;
                addcommit.Committee = true;
                addcommit.CommitteeType = "M";
                addcommit.CoyCode = company;
                addcommit.CreateDate = DateTime.Now;
                addcommit.Createdby = loguser;
                addcommit.MgtNo = commit.MgtNo;
                addcommit.MgtNoApproval = commit.MgtNoApproval;
                addcommit.OperationId = commit.OperationId;
                addcommit.BrCode = branch;
                setupUnitOfWork.Committee.Add(addcommit);
                setupUnitOfWork.Commit();
                return Json(commit);

            }
            else
            {
                addcommit.CreditMaxComteeAmt = commit.CreditMaxComteeAmt;
                addcommit.CreditMinMgt = commit.CreditMinMgt;
                addcommit.Committee = true;
                addcommit.CommitteeType = "M";
                addcommit.CoyCode = company;
                addcommit.CreateDate = DateTime.Now;
                addcommit.Createdby = loguser;
                addcommit.MgtNo = commit.MgtNo;
                addcommit.MgtNoApproval = commit.MgtNoApproval;
                addcommit.OperationId = commit.OperationId;
                addcommit.BrCode = branch;

                addcommit.BoardNo = commit.BoardNo;
                addcommit.CreditMaxBoardAmt = commit.CreditMaxBoardAmt;
                addcommit.BoardNoApproval = commit.BoardNoApproval;
                addcommit.CreditMinBoard = commit.CreditMinBoard;
                setupUnitOfWork.Committee.Add(addcommit);
                //setupUnitOfWork.Commit();
                //return Json(committee);


                TblBankingCommittee addbodcommittee = new TblBankingCommittee();

                addbodcommittee.BoardNo = commit.BoardNo;
                addbodcommittee.CreditMaxBoardAmt = commit.CreditMaxBoardAmt;
                addbodcommittee.BoardNoApproval = commit.BoardNoApproval;
                addbodcommittee.BrCode = branch;
                addbodcommittee.CreditMinBoard = commit.CreditMinBoard;
                addbodcommittee.Committee = true;
                addbodcommittee.CommitteeType = "B";
                addbodcommittee.CoyCode = company;
                addbodcommittee.CreateDate = DateTime.Now;
                addbodcommittee.Createdby = loguser;
                addbodcommittee.OperationId = commit.OperationId;

                addbodcommittee.CreditMaxComteeAmt = commit.CreditMaxComteeAmt;
                addbodcommittee.CreditMinMgt = commit.CreditMinMgt;
                addbodcommittee.MgtNo = commit.MgtNo;
                addbodcommittee.MgtNoApproval = commit.MgtNoApproval;
                setupUnitOfWork.Committee.Add(addbodcommittee);
                setupUnitOfWork.Commit();

                return Json(true);
            }
        }



        [HttpGet]
        public JsonResult GetOperation()
        {

            var list = new List<SelectTwoContentM>();

            var result = setupUnitOfWork.OperationLevel.GetAll();
            foreach (var item in result)
            {
                list.Add(new SelectTwoContentM
                {
                    id = Convert.ToString(item.OperationId),
                    text = item.Operations,
                });
            }
            return Json(list);
        }






        public class SelectTwoContentM
        {
            public string id { get; set; }
            public string text { get; set; }
        }


    }
}

TheCoreBanking 2.0/TheCoreBanking/Views/ApprovalCommittee/Index.cshtml
@model TheCoreBanking.Data.Models.TblBankingCommittee


<div class="card">
    <div class="card-header">
        <h4 class="card-title text-center"><small class="description">Credit Committee Approval Setup</small></h4>
    </div>
    <div class="card-body">
        <div id="committee-toolbar">
            <div class="form-group text-right">
                <button class="btn btn-danger pull-left" data-toggle="modal" data-target="#AddNewCommittee" type="button" value="Add Company" id="addclearcommittee" name="addclearcommittee">
                    <i class="now-ui-icons ui-1_simple-add"></i>
                    Add Committee
                </button>
            </div>
        </div>
        <table id="data-table" data-toggle="table"
               data-url="@Url.Action("listcommittee","ApprovalCommittee")"
               data-search="true"
               data-search-align="right"
               data-show-export="true"
               class="data-table"
               data-minimum-count-columns="2"
               data-pagination="true"
               data-show-pagination-switch="true"
               data-page-list="[10, 25, 50, 100, ALL]"
               data-mobile-responsive="true"
               data-toolbar="#committee-toolbar"
               data-show-refresh="true"
               data-show-toggle="true"
               data-show-columns="true"
               data-detail-view="true"
               data-unique-id="Id"
               data-checkon-init="true"
               data-buttons-class="danger">
            <thead>
                <tr>
                    <th data-field="Id" data-visible="false"></th>
                    <th data-field="mgtNo"><b>Management No</b></th>
                    <th data-field="mgtNoApproval"><b>Mgt Approval No</b></th>
                    <th data-field="boardNo"><b>Board No</b></th>
                    <th data-field="boardNoApproval"><b>B Approval No</b></th>
                </tr>
            </thead>
        </table>
    </div>
</div>





<div id="AddNewCommittee" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" id="closecommittee" name="closecommittee">&times;</button>
                <h7 class="modal-title">NEW COMMITTEE APPROVAL SETUP </h7>
            </div>
            <div class="modal-body">
                <form id="frmcommittee">
                    <div class="card card-plain">
                        <div class="card-header">
                            <h4 class="modal-title"> Management Committee</h4>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    Number of Persons:
                                    <input id="MgtNo" class="form-control" />
                                </div>
                                <div class="form-group col-md-6">
                                    Number of Person for Final Approval Decision:
                                    <input id="MgtNoApproval" class="form-control" />
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    Minimum Amount
                                    <input id="CreditMinMgt" type="number" class="form-control text-right" />
                                </div>
                                <div class="form-group col-md-6">
                                    Maximum Amount
                                    <input id="CreditMaxComteeAmt" type="number" class="form-control text-right" />
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    Operation
                                    <select id="OperationM" name="OperationM" class="form-control text-right">
                                        <option>Select Operation</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row mb-2 required">
                                <div class="form-group col-md-6">
                                    <div class="form-check form-check-inline">
                                        <label class="form-check-label">
                                            <b>ADD BOARD COMMITTEE</b>
                                            <input type="checkbox" id="clicked" name="clicked" value="boardCommit" class="form-check-input">
                                            <span class="form-check-sign"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div id="bcc" style="display:none">
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Number of Persons:
                                        <input id="BoardNo" class="form-control" />
                                    </div>
                                    <div class="form-group col-md-6">
                                        Number of Persons for Approval Decision:
                                        <input id="BoardNoApproval" required class="form-control" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        Minimum Amount
                                        <input id="CreditMinBoard" class="form-control text-right" />
                                    </div>
                                    <div class="form-group col-md-6">
                                        Maximum Amount
                                        <input id="CreditMaxBoardAmt" class="form-control text-right" />
                                    </div>
                                </div>
                                <div class="form-group text-right">
                                    <button class="btn btn-info" id="btnCommit" type="submit" value="Save Record">
                                        <i class="now-ui-icons ui-1_check"></i>
                                        Save Record
                                    </button>
                                    <button class="btn btn-danger" id="btnclear" type="button" onclick="clear()">
                                        <i class="fa fa-remove"></i>
                                        Clear
                                    </button>
                                </div>
                            </div>


                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>





@section Scripts {
    <environment include="Development">
        <script src="~/js/committee.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/committee.min.js"></script>
    </environment>
}